# Generated by Django 5.1.3 on 2024-11-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerstack',
            name='delivery_date',
            field=models.DateField(),
        ),
    ]
