FROM node:18.19.0 AS build-stage
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json ./
RUN npm install

COPY . ./
RUN npm run build

FROM nginx:stable-alpine 
COPY --from=build-stage /app/dist /usr/share/nginx/html
COPY --from=build-stage /app/images /usr/share/nginx/html/images
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 82
CMD ["nginx", "-g", "daemon off;"]